
services:
 
  postgres:
    image: postgres:15
    container_name: campus_bus_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Postgre@715
      POSTGRES_DB: campus_bus_db
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
 
  fastapi:
    build: 
      context: ../backend
      dockerfile: DockerFile
    container_name: campus_bus_api
    ports:
      - '8000:8000'
    environment:
      DATABASE_URL: postgresql://postgres:Postgre@715@postgres:5432/campus_bus_db
      SECRET_KEY: my-very-secret-jwt-key-change-in-production
      ALGORITHM: HS256
      ACCESS_TOKEN_EXPIRE_MINUTES: '60'
    depends_on:
      - postgres
    volumes:
      - ../backend:/app
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
 
volumes:
  postgres_data:
